CREATE TABLE streamlocal.video_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id UUID NOT NULL,
    file_role VARCHAR(32) NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    storage_path TEXT NOT NULL,
    width_pixels INTEGER,
    height_pixels INTEGER,
    bitrate_kbps INTEGER,
    codec VARCHAR(100),
    file_size_bytes BIGINT,
    checksum VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_video_files_video
        FOREIGN KEY (video_id)
        REFERENCES streamlocal.videos (id)
        ON DELETE CASCADE,

    CONSTRAINT uq_video_files_storage_path
        UNIQUE (storage_path),

    CONSTRAINT chk_video_files_role
        CHECK (file_role IN ('SOURCE', 'RENDITION', 'SUBTITLE')),

    CONSTRAINT chk_video_files_dimensions
        CHECK (
            (width_pixels IS NULL AND height_pixels IS NULL)
            OR
            (width_pixels IS NOT NULL AND height_pixels IS NOT NULL AND width_pixels > 0 AND height_pixels > 0)
        ),

    CONSTRAINT chk_video_files_bitrate
        CHECK (bitrate_kbps IS NULL OR bitrate_kbps > 0),

    CONSTRAINT chk_video_files_size
        CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),

    CONSTRAINT chk_video_files_subtitle_shape
        CHECK (
            file_role <> 'SUBTITLE'
            OR (
                width_pixels IS NULL
                AND height_pixels IS NULL
                AND bitrate_kbps IS NULL
                AND codec IS NULL
            )
        )
);

CREATE UNIQUE INDEX uq_video_files_source_per_video
    ON streamlocal.video_files (video_id)
    WHERE file_role = 'SOURCE';

CREATE UNIQUE INDEX uq_video_files_subtitle_per_video
    ON streamlocal.video_files (video_id)
    WHERE file_role = 'SUBTITLE';

CREATE UNIQUE INDEX uq_video_files_rendition_resolution_per_video
    ON streamlocal.video_files (video_id, width_pixels, height_pixels)
    WHERE file_role = 'RENDITION';